# -*- coding: utf-8 -*-
"""23/09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ptCxA6mOE_M4ZVzeeD5Mrm6amAhhwhjO
"""

import re
sn= input('Voce quer continuar no sistema? (s/n): ')
arrumar=sn.lower()
arrumar1=arrumar.strip()
padrao= r'[s]{1}'
if re.fullmatch(padrao, arrumar1):
  print('Continuando')
else:
  print('Encerrando')

estado = input('Coloque a sigla do seu estado: ')
padrao= estado.upper()
padrao1= padrao.strip()
print(f'Seu estado é {padrao1}')

desconto ='CUPOM10'
print(f'Esses sao os descontos {Desconto}')
digite= input("EScreva o cupom: ").upper()
if desconto==digite:
  print('Desconto aceito.')
else:
  print('Cupom invalido')

nome=input('Digite seu nome: ').strip()
print(nome)
print(len(nome))

email= input('Digite seu email: ')
arrumar= email.strip().lower()
if email == arrumar:
  print('Email correto')
else:
  print('Erro: O campo e-mail não pode ficar em branco!')

Usuarioc= 'aluno@escola.com'
usuario= input('Digite o login: ').lower().strip()
if usuarioc == usuario:
  print('Login correto')